#!/bin/bash

BENCHMARK="$1"
OUTDIR="$2"

echo "; run solver"
./smtcomp_solver ${BENCHMARK} > proof.txt 2>${OUTDIR}/solver-error.log

echo "; compressing proof"
PROOF_SIZE=`stat --printf="%s" proof.txt`
gzip -c proof.txt > ${OUTDIR}/proof.txt.gz
COMPRESS_SIZE=`stat --printf="%s" ${OUTDIR}/proof.txt.gz`
echo "; proof size: ${PROOF_SIZE} (${COMPRESS_SIZE} compressed)"

echo "; checking proof"
./smtcomp_checker ${BENCHMARK} proof.txt 2>${OUTDIR}/checker-error.log
echo "proofsize=${PROOF_SIZE}"
echo "compressedsize=${COMPRESS_SIZE}"
