#!/bin/bash

BENCHMARK="$1"
OUTDIR="$2"

echo "; run solver"
./smtcomp_solver ${BENCHMARK} > proof.txt 2>${OUTDIR}/solver-error.log
if [ `stat --printf="%s" ${OUTDIR}/solver-error.log` -gt 10000000 ]; then
    truncate -s 10M ${OUTDIR}/solver-error.log
fi

echo "; compressing proof"
PROOF_SIZE=`stat --printf="%s" proof.txt`
if [ "$PROOF_SIZE" -lt 1000000000 ]; then
    gzip -c proof.txt > ${OUTDIR}/proof.txt.gz
    COMPRESS_SIZE=`stat --printf="%s" ${OUTDIR}/proof.txt.gz`
fi
echo "; proof size: ${PROOF_SIZE} (${COMPRESS_SIZE} compressed)"

echo "; checking proof"
./smtcomp_checker ${BENCHMARK} proof.txt 2>${OUTDIR}/checker-error.log
if [ `stat --printf="%s" ${OUTDIR}/checker-error.log` -gt 10000000 ]; then
    truncate -s 10M ${OUTDIR}/checker-error.log
fi
echo "proofsize=${PROOF_SIZE}"
echo "compressedsize=${COMPRESS_SIZE}"
