#!/bin/bash

# Jochen Hoenicke
# A simple post-processor for SMT.

STATUS=$(
# remove the StarExec timing information from each line of the solver output
    sed 's/^[0-9]*\.[0-9]*\/[0-9]*.[0-9]*\t//g' "$1" | \
# filter out lines containing only sat, unsat, or unknown
    egrep -e '^\s*(sat|unsat|unknown)\s*$' | \
# the first answer wins
    head -1 | egrep -o '(sat|unsat|unknown)')

if [[ "$STATUS" == "sat" ]]; then
    # the output contains only the word "sat"
    echo "starexec-result=sat"
elif [[ "$STATUS" == "unsat" ]]; then
    # the output contains only the word "unsat"
    echo "starexec-result=unsat"
else
    echo "starexec-result=starexec-unknown"
fi
