#!/bin/bash

# Jochen Hoenicke

# A simple post-processor for SMT.
# The logic is:
# - remove success outputs (they're ignored for now)
# - take the first line
# - all other lines after it ignored
# - if the line is sat, unsat, or unknown this is the status
# - if no such line exists, the status is unknown.
# - all lines after the result are ignored.


STATUS=$(
# remove the StarExec timing information from each line of the solver output
    sed 's/^[0-9]*\.[0-9]*\/[0-9]*.[0-9]*\t//g' "$1" | \
# remove empty lines and lines containing only success or a comment
    egrep -v -e '^\s*(success|;.*)?\s*$' | \
# the first answer wins
    head -1 | sed 's/^\s*\([a-z]\+\)\b.*/\1/')

if [[ "$STATUS" == "sat" ]]; then
    # the output contains only the word "sat"
    echo "starexec-result=sat"
elif [[ "$STATUS" == "unsat" ]]; then
    # the output contains only the word "unsat"
    echo "starexec-result=unsat"
else
    echo "starexec-result=starexec-unknown"
fi
