#!/bin/sh

# This is a wrapper script that allows the model validator to be used as a
# postprocessor on StarExec.

# $1: model
# $2: benchmark after preprocessing

# remove the StarExec timing information from each line of the solver output
sed 's/^[0-9]*\.[0-9]*\/[0-9]*.[0-9]*\t//g' "$1" | \
# remove success response lines from solver output
grep -v '^success$' > ./cleanSolverOutput.txt

PYTHONPATH="pysmt" python2 ModelValidator.py --smt2 $2 --model ./cleanSolverOutput.txt

