#!/bin/sh

# This is a wrapper script that allows the model validator to be used as a
# postprocessor on StarExec.

# $1: model
# $2: benchmark after preprocessing
sed -i 's/^[0-9]*\.[0-9]*\/[0-9]*.[0-9]*\t//g' $1
PYTHONPATH="pysmt" python2 ModelValidator.py --smt2 $2 --model $1

